name: gene-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - numpy=1.26.4
  - pandas=2.1.4
  - biopython=1.81
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - tqdm=4.66.1
  - openpyxl=3.1.2
  - pip
  - pip:
    - streamlit==1.32.0
    - streamlit-option-menu==0.3.6